### PR TITLE
update a java option.

### PR DESCRIPTION
**Pull request by wenhoujx**
hello, i think i spot something that's clearly wrong, so i tries to fix. 

Can you point me to where is the source or doc of these settings so i can fix the lisp docstring too ? 

```
(defcustom lsp-java-selection-enabled t
  "Enable/disable the 'auto build'"
  :type 'boolean
  :group 'lsp-java)

```

### CODE REVIEW

**Comment by wenhoujx** [comment]
is it from here? https://marketplace.visualstudio.com/items?itemName=redhat.java 

i don't see a `selection.enabled` option. are these settings used by language server? if so, can someone points me to the jdt server doc about these? 

Thanks

**Comment by yyoncho** [comment]
most likely it is typo and it should be this: https://github.com/redhat-developer/vscode-java/blob/master/package.json#L581

**Comment by wenhoujx** [comment]
i found the source of truth! https://github.com/eclipse/eclipse.jdt.ls/blob/13ec1ad86e6509702fe01dd2d8df4fbfa99e5f00/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java#L488

**Comment by wenhoujx** [comment]
@yyoncho  updated, can you take a look and let me know? thanks!

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
Thank you!

**Pull request merged**
