### PR TITLE
Add resolveAdditionalTextEditsSupport capability to speed up completion

### PR DESCRIPTION
**Pull request by rrudakov**
Based on [this](https://github.com/eclipse/eclipse.jdt.ls/pull/1487) and [this](https://github.com/redhat-developer/vscode-java/pull/1503)

### CODE REVIEW

**Comment by yyoncho** [comment]
This is not sufficient. We have to implement it in lsp-mode as well otherwise the additional text edits won't be applied.

cc @kiennq

**Comment by kiennq** [comment]
Let me make sure if I understand this correctly, we will allow `resolveAdditionalTextEditsSupport`, and will always resolve completion item when determine it from the popup?
Is there server capability corresponding to this so I can choose to resolve completion item or not?

**Comment by yyoncho** [comment]
thank you!

**Comment by rrudakov** [comment]
Thanks a lot!

**Pull request merged**
