### PR TITLE
Add makefile for GH actions

### PR DESCRIPTION
**Pull request by ericdallo**
Currently, there're some warnings/errors that we need to investigate if we can fix it or ignore:

`make build`
`make compile`
```bash
In toplevel form:
lsp-java-boot.el:29:1: Error: Package cl is deprecated

In toplevel form:
lsp-java.el:446:61: Error: Unused lexical argument ‘command’
[Treemacs] Warning: couldn’t find hl-line-mode’s background color for icons, falling back on unspecified-bg.

In toplevel form:
lsp-jt.el:35:1: Error: defcustom for ‘lsp-jt-theme’ fails to specify containing group
```

`make checkdoc`
```bash
Warning (emacs): 
lsp-java-boot.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
lsp-java-boot.el:37: There should be two spaces after a period
Warning (emacs): 
lsp-java-boot.el:52: Argument ‘params’ should appear (as PARAMS) in the doc string
Warning (emacs): 
lsp-java-boot.el:60: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java-boot.el:88: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java-boot.el:91: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:117: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:122: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:127: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:133: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:138: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:167: First sentence should end with punctuation
Warning (emacs): 
lsp-java.el:171: First sentence should end with punctuation
Warning (emacs): 
lsp-java.el:175: First sentence should end with punctuation
Warning (emacs): 
lsp-java.el:179: First sentence should end with punctuation
Warning (emacs): 
lsp-java.el:183: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:188: First sentence should end with punctuation
Warning (emacs): 
lsp-java.el:192: First sentence should end with punctuation
Warning (emacs): 
lsp-java.el:196: First sentence should end with punctuation
Warning (emacs): 
lsp-java.el:200: First sentence should end with punctuation
Warning (emacs): 
lsp-java.el:209: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:220: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:221: There should be two spaces after a period
Warning (emacs): 
lsp-java.el:220: There should be two spaces after a period
Warning (emacs): 
lsp-java.el:226: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:226: There should be two spaces after a period
Warning (emacs): 
lsp-java.el:232: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:237: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:242: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:251: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:260: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:261: There should be two spaces after a period
Warning (emacs): 
lsp-java.el:266: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:295: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:300: First line is not a complete sentence
Warning (emacs): 
lsp-java.el:302: There should be two spaces after a period
Warning (emacs): 
lsp-java.el:300: There should be two spaces after a period
Warning (emacs): 
lsp-java.el:445: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:451: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:575: Argument ‘callback’ should appear (as CALLBACK) in the doc string
Warning (emacs): 
lsp-java.el:611: All interactive functions should have documentation
Warning (emacs): 
lsp-java.el:786: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:792: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:858: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:892: Argument ‘response’ should appear (as RESPONSE) in the doc string
Warning (emacs): 
lsp-java.el:892: Probably "CHANGES" should be imperative "Change"
Warning (emacs): 
lsp-java.el:899: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:916: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:932: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:943: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:959: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:978: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1007: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1034: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1045: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1049: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1080: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1093: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1109: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1142: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1174: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1322: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-java.el:1331: All interactive functions should have documentation
Warning (emacs): 
lsp-java.el:425: Error messages should *not* end with a period
Warning (emacs): 
lsp-java.el:612: Messages should start with a capital letter
Warning (emacs): 
lsp-java.el:853: Error messages should *not* end with a period
Warning (emacs): 
lsp-java.el:905: There should be two spaces after a period
Warning (emacs): 
lsp-java.el:905: ‘y-or-n-p’ argument should end with "? "
Warning (emacs): 
lsp-java.el:922: There should be two spaces after a period
Warning (emacs): 
lsp-java.el:922: ‘y-or-n-p’ argument should end with "? "
Warning (emacs): 
lsp-java.el:1121: Error messages should *not* end with a period
Warning (emacs): 
lsp-java.el:1159: Error messages should *not* end with a period
Warning (emacs): 
lsp-jt.el:50: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:73: All interactive functions should have documentation
Warning (emacs): 
lsp-jt.el:123: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:168: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:183: All interactive functions should have documentation
Warning (emacs): 
lsp-jt.el:207: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:215: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:254: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:268: All interactive functions should have documentation
Warning (emacs): 
lsp-jt.el:272: All interactive functions should have documentation
Warning (emacs): 
lsp-jt.el:280: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:310: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:330: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:339: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:351: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:360: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:391: All interactive functions should have documentation
Warning (emacs): 
lsp-jt.el:404: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:409: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:418: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:426: All interactive functions should have documentation
Warning (emacs): 
lsp-jt.el:439: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:538: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:548: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:553: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:567: All variables and subroutines might as well have a documentation string
Warning (emacs): 
lsp-jt.el:578: All interactive functions should have documentation
Warning (emacs): 
lsp-jt.el:140: Error messages should *not* end with a period
```

`make lint`
```bash
lsp-java-boot.el:1:0: error: Package should have a ;;; Commentary section.
lsp-java-boot.el:1:0: error: package.el cannot parse this buffer: Search failed: ";;; lsp-java.el ends here"
lsp-java-boot.el:4:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
lsp-java-boot.el:29:10: warning: Replace deprecated `cl' with `cl-lib'.  The `cl-libify' package can help with this.
lsp-java.el:5:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
lsp-java.el:90:0: error: "lsp-jt-root" doesn't start with package's prefix "lsp-java".
lsp-jt.el:1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
lsp-jt.el:1:0: error: Package should have a Homepage or URL header.
lsp-jt.el:1:0: warning: The package summary should start with an uppercase letter or a digit.
lsp-jt.el:1:50: warning: You should depend on (emacs "24") if you need lexical-binding.
lsp-jt.el:6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
lsp-jt.el:39:0: error: "lsp-test-java-browser-position-params" doesn't start with package's prefix "lsp-jt".
lsp-jt.el:44:0: error: "lsp-test-java-report-position-params" doesn't start with package's prefix "lsp-jt".
lsp-jt.el:70:1: error: You should depend on (emacs "24.3") if you need `defvar-local'.
lsp-jt.el:73:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
lsp-jt.el:99:29: error: You should depend on (emacs "25.1") if you need `when-let'.
lsp-jt.el:118:5: error: You should depend on (emacs "24.3") if you need `setq-local'.
lsp-jt.el:120:7: error: You should depend on (emacs "24.3") if you need `setq-local'.
lsp-jt.el:136:24: error: You should depend on (emacs "24.1") if you need `get-mru-window'.
lsp-jt.el:140:5: error: You should depend on (emacs "24.3") if you need `user-error'.
lsp-jt.el:167:0: error: "java-tests--roots" doesn't start with package's prefix "lsp-jt".
lsp-jt.el:193:8: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-labels'.
lsp-jt.el:217:8: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-case'.
lsp-jt.el:254:3: error: You should depend on (emacs "25.1") if you need `if-let'.
lsp-jt.el:260:5: error: You should depend on (emacs "24.3") if you need `user-error'.
lsp-jt.el:294:38: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-first'.
lsp-jt.el:304:38: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-first'.
lsp-jt.el:310:15: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-second'.
lsp-jt.el:377:28: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-list*'.
lsp-jt.el:392:3: error: You should depend on (emacs "25.1") if you need `if-let'.
lsp-jt.el:393:22: error: You should depend on (emacs "24.3") if you need `display-buffer-in-side-window'.
lsp-jt.el:395:20: error: You should depend on (emacs "24.3") if you need `display-buffer-in-side-window'.
lsp-jt.el:401:7: error: You should depend on (emacs "24.3") if you need `setq-local'.
lsp-jt.el:427:3: error: You should depend on (emacs "25.1") if you need `when-let'.
lsp-jt.el:435:26: error: You should depend on (emacs "24.1") if you need `get-mru-window'.
lsp-jt.el:441:7: error: You should depend on (emacs "24.1") if you need `pcase'.
lsp-jt.el:492:10: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-rest'.
lsp-jt.el:511:30: error: You should depend on (emacs "25.1") if you need `when-let'.
lsp-jt.el:543:19: error: You should depend on (emacs "25.1") if you need `alist-get'.
lsp-jt.el:553:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
lsp-jt.el:580:18: error: You should depend on (emacs "24.3") if you need `display-buffer-in-side-window'.
lsp-jt.el:585:5: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

We can choose to ignore `checkdoc` and `package-lint` as a start.

### CODE REVIEW

**Comment by ericdallo** [comment]
@yyoncho, Fixed all `lint` and `byte-compile` errors but one that already has an [issue](https://github.com/Alexander-Miller/treemacs/issues/654) on `treemacs`.

Could you take a look and check if my changes are ok? I tried to change the minimum possible.

**Comment by yyoncho** [comment]
Thank you, that is a tremendous job! Is this ready to be merged? Are we going to remove travis as part of this change?

**Comment by ericdallo** [comment]
I removed travis :)
About the GH action, we may have warnings/erros that we'll need to fix for emacs older versions (local I'm testing with emacs snapshot).
So I think we can merge and check the action GH action status, then I can open another PR fixing the warnings/errors, what do you think @yyoncho ?

**Comment by yyoncho** [comment]
> So I think we can merge and check the action GH action status, then I can open another PR fixing the warnings/errors, what do you think @yyoncho ?

I am fine with that and it is definitely a step forward.

**Comment by ericdallo** [comment]
Oh, forget it, we can test it from here: https://github.com/ericdallo/lsp-java/actions?query=workflow%3ACI

**Comment by yyoncho** [comment]
One more thing - can we update the readme link with the new status?

**Comment by ericdallo** [comment]
Sure, when everything is working, I'll generate the github badge!

**Pull request merged**
