### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by ericdallo**
* Fix ci tests
* change badge for github action badge

### CODE REVIEW

**Comment by ericdallo** [comment]
@yyoncho, It's working now.
I don't have permissions, so could you change on repo `Settings` to run CI GH actions on PRs?

**Comment by yyoncho** [comment]
I added you as a collaborator. I am not sure where to do that from.

**Comment by ericdallo** [comment]
Thanks for that, I accepted the invitation but I can't access the settings yet :/
image

**Comment by yyoncho** [comment]
Can you retry now?

**Comment by ericdallo** [comment]
It shows me the settings, but I can't see the `branches` section
image

If you prefer, I can explain the steps to activate this check on PRs feature

**Comment by yyoncho** [comment]
Sorry, now it should be good. I dint saw that there is a more powerful role than "Admin"

**Comment by ericdallo** [comment]
No problem, thanks!
Done, If you want to change/customize that latter, it's on `Settings` -> `Branches` -> `Branch protection rules` -> `master` :)

**Comment by ericdallo** [comment]
For some weird reason this PR is not running the actions, I think because we enabled the checks after the PR was created...
On my fork it's passing normal: https://github.com/ericdallo/lsp-java/actions/runs/87675675

**Comment by ericdallo** [comment]
Well, I'll merge it and we can check if it's triggered on master.

**Comment by ericdallo** [comment]
All passing and OK on master :)

image

image

**Pull request merged**
