### PR TITLE
test: Emacs 29.1

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Comment by jcs090218** [comment]
cc @yyoncho

Can you give me merge permission to all repositories so I don't have to ping you everywhere with these kinds of updates (mainly CI updates)? 😅

**Comment by yyoncho** [comment]
can you check if this permission is sufficient?

**Comment by jcs090218** [comment]
> can you check if this permission is sufficient?

Nope, not on this repository. 🤔

**Comment by jcs090218** [comment]
Umm... actually I don't know. Does that mean I can merge on this repo? 🤔

**Comment by yyoncho** [comment]
Can you try now?

**Comment by jcs090218** [comment]
Yes! I can! Thank you! 🚀

**Comment by jcs090218** [comment]
Can you also give me push permission to these repositories?

- ccls
- lsp-mssql
- lsp-sourcekit
- lsp-docker
- lsp-haskell
- lsp-sonarlint
- lsp-metals

Thank you!

**Comment by yyoncho** [comment]
I will do that later today

**Comment by yyoncho** [comment]
@jcs090218 just did it. Let me know if I have missed something.

**Comment by jcs090218** [comment]
👌 Thank you very much! 😁

**Comment by yyoncho** [comment]
Thank you for taking care of this!

**Pull request merged**
